### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [shigeyukioba/matchernet#58]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary matchernet -w /tmp/ext matchernet==0.1.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting matchernet==0.1.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/648/a24270e1c7114/matchernet-0.1.0.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-rhik1j19/matchernet/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-rhik1j19/matchernet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-rhik1j19/matchernet/pip-egg-info
         cwd: /tmp/pip-wheel-rhik1j19/matchernet/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-rhik1j19/matchernet/setup.py", line 29, in <module>
        with open('readme.md', encoding='utf-8') as f:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
I can't verify the autofix because opencv-python==4.0.0.21 doesn't exist anymore
